export type GoldenOutcome = "PASS" | "PARTIAL" | "UNSUPPORTED_SAFE" | "FAIL";
export type GoldenQuestion = { query: string; expected: GoldenOutcome; note: string };

export const CONTRACTOR_SEARCH_GOLDEN_QUESTIONS: GoldenQuestion[] = [
  ["roofers in Broward County", "PASS", "trade and county"],
  ["active roofers in Broward County", "PASS", "status, trade and county"],
  ["plumbers in New Jersey", "PASS", "NJ specialty coverage"],
  ["HVAC contractors in Florida", "PASS", "Florida class mapping"],
  ["home improvement contractors in New Jersey", "PASS", "NJ HIC mapping"],
  ["CCC1332036", "PASS", "exact Florida credential"],
  ["license CCC1332036", "PASS", "credential prefix"],
  ["Restorations Florida LLC", "PASS", "company identity"],
  ["roofers in Palm Beach County with enforcement records", "PARTIAL", "indexed source rows; contractor attribution gate remains closed"],
  ["contractors with stop-work evidence", "PARTIAL", "source rows are not contractor-joinable"],
  ["roofers with permit records", "UNSUPPORTED_SAFE", "local permit coverage only"],
  ["I need someone to replace my roof in Deerfield Beach", "PASS", "consumer language and recorded county"],
  ["I want to check whether this roofer is licensed", "PARTIAL", "needs identity or geography"],
  ["electricians in Palm Beach County", "PARTIAL", "Florida electrical source limitation"],
  ["general contractors in Miami-Dade", "PASS", "trade and county"],
  ["contractor with license CGC1520610", "PASS", "exact credential"],
  ["contractors with no complaints", "UNSUPPORTED_SAFE", "complaint universe unavailable"],
  ["best roofer in Broward", "UNSUPPORTED_SAFE", "no provider-quality ranking"],
  ["cheapest contractor near me", "UNSUPPORTED_SAFE", "no price ranking or inferred location"],
  ["contractor serving my address", "UNSUPPORTED_SAFE", "HQ is not service territory"],
  ["active roofing contractors in Florida", "PASS", "statewide Florida cohort"],
  ["current licensed plumbers in Florida", "PASS", "current status mapping"],
  ["active roofers in Broward County with enforcement records", "PARTIAL", "combined interpretation; contractor evidence attribution remains gated"],
  ["licensed HVAC contractors in Florida with permit evidence", "UNSUPPORTED_SAFE", "permit joins unavailable"],
  ["I am worried my contractor may not be properly licensed", "PARTIAL", "needs exact identity"],
  ["I want to check whether this roofer has regulatory problems", "PARTIAL", "needs identity/geography"],
  ["I need a licensed contractor for an electrical job in Palm Beach County", "PARTIAL", "electrical source limitation"],
  ["Vulcan Contractors Group", "PASS", "company identity"],
  ["CGC1520610", "PASS", "exact credential"],
  ["roofing Broward", "PASS", "abbreviated trade/place"],
  ["roofer Browerd County", "PARTIAL", "typo suggestion without silent rewrite"],
  ["air conditioning contractors Palm Beach", "PASS", "trade synonym"],
  ["AC contractors in Florida", "PASS", "short-token HVAC synonym"],
  ["GC in Florida", "PASS", "short-token general synonym"],
  ["plumbing contractors FL", "PASS", "state abbreviation"],
  ["roof contractors Miami", "PASS", "trade/county synonym"],
  ["certified roofing contractors Florida", "PASS", "classification phrase"],
  ["registered roofing contractors Florida", "PASS", "classification phrase"],
  ["pool contractors in Florida", "PASS", "pool/spa mapping"],
  ["solar contractors in Florida", "PASS", "solar mapping"],
  ["mechanical contractors in Florida", "PASS", "mechanical distinct from HVAC"],
  ["residential contractors in Florida", "PASS", "residential mapping"],
  ["building contractors in Florida", "PASS", "building mapping"],
  ["Florida contractors with DBPR discipline", "PARTIAL", "indexed source rows"],
  ["Florida unlicensed activity records", "PARTIAL", "indexed source rows"],
  ["Florida recovery fund records", "PARTIAL", "indexed source rows"],
  ["no enforcement records roofing Florida", "UNSUPPORTED_SAFE", "absence cannot be proven"],
  ["safest contractor", "UNSUPPORTED_SAFE", "no safety ranking"],
  ["top contractors", "UNSUPPORTED_SAFE", "no quality ranking"],
  ["contractors with insurance", "UNSUPPORTED_SAFE", "no comparable current certificate universe"],
  ["", "UNSUPPORTED_SAFE", "empty prompt"],
  ["<script>alert(1)</script>", "UNSUPPORTED_SAFE", "garbage is not executable"],
  ["x".repeat(250), "UNSUPPORTED_SAFE", "input is bounded to 180 characters at UI/planner"],
  ["active expired roofers in Broward", "UNSUPPORTED_SAFE", "contradictory statuses"],
  ["public work contractors registered in New York", "PASS", "NYSDOL public-work registry snapshot"],
  ["is my New York home-improvement contractor licensed?", "UNSUPPORTED_SAFE", "local HIC vs public-work registration"],
  ["New York mold remediation contractor", "UNSUPPORTED_SAFE", "mold bulk not acquired"],
  ["New York asbestos contractor", "UNSUPPORTED_SAFE", "asbestos contractor license vs worker cert"],
  ["is this contractor debarred?", "UNSUPPORTED_SAFE", "exact-id debarment path only"],
  ["best contractor in New York", "UNSUPPORTED_SAFE", "no ranking"],
] .map(([query, expected, note]) => ({ query, expected, note })) as GoldenQuestion[];

export const GOLDEN_SCORE = CONTRACTOR_SEARCH_GOLDEN_QUESTIONS.reduce(
  (score, row) => ({ ...score, [row.expected.toLowerCase()]: score[row.expected.toLowerCase() as keyof typeof score] + 1 }),
  { pass: 0, partial: 0, unsupported_safe: 0, fail: 0 }
);
