/** DSPS published class totals, not licensee rows or a deduplicated business census. */
export const WI_SNAPSHOT = {
  sourceDate: "2026-09-22",
  retrievedAt: "2026-09-29",
  generatedAt: "2026-09-29",
  countsUrl: "https://dsps.wi.gov/seeking-information/monthly-license-counts/",
  lookupUrl: "https://license.wi.gov/s/license-lookup",
  ordersUrl: "https://dsps.wi.gov/seeking-information/orders-and-disciplinary-actions/",
  complaintsUrl: "https://dsps.wi.gov/seeking-information/file-a-complaint/",
  listUrl: "https://dsps.wi.gov/Pages/SelfService/OrderListofLicensees.aspx",
  classes: [
    { code: "DCFR", label: "Dwelling Contractor", grain: "business", active: 9895, inactive: 7828 },
    { code: "DCFRR", label: "Dwelling Contractor Restricted", grain: "business", active: 66, inactive: 137 },
    { code: "EC", label: "Electrical Contractor", grain: "business", active: 3507, inactive: 1799 },
    { code: "HVACCONT", label: "HVAC Contractor", grain: "business", active: 2804, inactive: 2184 },
    { code: "HVACQ", label: "HVAC Qualifier", grain: "person", active: 608, inactive: 215 },
    { code: "ME", label: "Master Electrician", grain: "person", active: 6121, inactive: 1502 },
    { code: "JE", label: "Journeyman Electrician", grain: "person", active: 7423, inactive: 2831 },
    { code: "PM", label: "Master Plumber", grain: "person", active: 2890, inactive: 618 },
  ],
  qualifier: { code: "DCQ", label: "Dwelling Contractor Qualifier", grain: "person", count: null, reason: "DSPS count table duplicates the row and labels it F, while DSPS identifies this as an individual credential." },
  credentialRows: 0,
  disciplinaryRows: 0,
  exactDisciplinaryAttachments: 0,
  nameOnlyAdverseJoins: 0,
  newCanonicalCompanies: 0,
  graphWrites: 0,
  claimEligibilityChanges: 0,
} as const;
