export const WV_SNAPSHOT = {
  ticket: "WV-CON-001",
  regulator: "West Virginia Division of Labor",
  licensingBoard: "West Virginia Contractor Licensing Board",
  retrievedAt: "2026-10-06",
  elevatorInspectors: {
    title: "Elevator Inspectors List",
    url: "http://www.wvlabor.com/new_searches/elevators_RESULTS.cfm",
    httpDate: "Tue, 06 Oct 2026 19:25:04 GMT",
    httpLastModified: "NOT_SENT",
    bytes: 28293,
    sha256: "c26453628399a63c853e0dc23b34d591cd47646dd92225f6f5fd3199571038ca",
    listAsOfDate: "NOT_PRINTED",
    inspectorRows: 23,
    distinctInspectorNameStrings: 23,
    distinctBusinessNameStrings: 17,
    businessNameStringsAreResolvedEntities: false,
    statusNotesStillOnList: 2,
    statusNotesRemovedFromCount: false,
    personIsNotACompany: true,
    isContractorLicense: false,
  },
  contractorLicenseRoster: "NOT_ACQUIRED",
  hvacCertificationRoster: "NOT_ACQUIRED",
  plumbingCertificationRoster: "NOT_ACQUIRED",
  manufacturedHousingRoster: "NOT_ACQUIRED",
  verifySearchUrl: "https://wvclboard.wv.gov/verify",
  verifySearchIsBulkRoster: false,
  databaseSearchUrl: "https://labor.wv.gov/database-search",
  databaseSearchIsBulkRoster: false,
  combinedContractorDenominator: null,
  graphWrites: 0,
  newCanonicalEntities: 0,
  nameOnlyAdverseJoins: 0,
  aggregateRating: null,
  trustScore: null,
} as const;
