export const AR_SNAPSHOT = {
  regulator: "Arkansas Contractors Licensing Board",
  department: "Arkansas Department of Labor and Licensing",
  sourceUrl: "https://www.discover.arkansas.gov/_docs/Publications/Licensed-Occupations/DLO.pdf",
  sourceTitle: "August 2026 Directory of Licensed Occupations",
  sha256: "b71798b59a6ae508544470ef179d8eb7475731c54ffb93f9d941989ceb27e64e",
  bytes: 2149502,
  pages: 416,
  httpLastModified: "2026-09-30T14:14:39Z",
  examinedAt: "2026-10-06",
  combinedContractorDenominator: null,
  activeRoster: "NOT_ACQUIRED",
  qualifyingPartySplit: "NOT_SPLIT",
  personCompanySplit: "NOT_SPLIT",
  newCanonicalEntities: 0,
  existingMatches: "NOT_ACQUIRED",
  evidenceAttachments: 0,
  graphWrites: 0,
  enforcementCorpus: "NOT_ACQUIRED",
  otherBoards: "NOT_ACQUIRED",
  classes: [
    {
      id: "commercial",
      label: "Commercial license",
      count: 8244,
      clock: "Number of licenses issued during a specific period 2025",
      grain: "Issuance during 2025. Not an active roster. The $50,000 commercial threshold excludes single-family residential projects.",
    },
    {
      id: "commercial-subcontractor",
      label: "Registered commercial subcontractor",
      count: 783,
      clock: "Number of licenses issued during a specific period 2025",
      grain: "Issuance during 2025. The description prints a $10,000 contractors surety bond as a requirement. A requirement is not an observed filing.",
    },
    {
      id: "residential-building",
      label: "Residential building contractor",
      count: 2762,
      clock: "Number of licenses issued during a specific period 2025",
      grain: "Issuance during 2025 for single-family new construction of one to four units. Not the commercial license.",
    },
    {
      id: "home-improvement",
      label: "Residential home improvement specialty contractor",
      count: 5822,
      clock: "Number of licenses issued during a specific period 2025",
      grain: "Issuance during 2025. Limited and unlimited home-improvement authority are not split inside this figure.",
    },
    {
      id: "remodeler",
      label: "Residential remodeler contractor",
      count: 1868,
      clock: "Total number of licenses, as of point in time 2023",
      grain: "A 2023 point-in-time total. Not a 2025 issuance figure and not added to the other classes.",
    },
    {
      id: "roofer",
      label: "Residential roofers registration",
      count: 750,
      clock: "Number of licenses issued during a specific period 2024",
      grain: "Issuance during 2024. The description prints a $15,000 surety bond as a requirement. A requirement is not an observed filing.",
    },
  ],
} as const;
