/**
 * SC-CON-001: LLR FY2025 annual-report category counts.
 * No license-row roster was loaded. These are printed category totals.
 */
export const SC_CLB_CATEGORIES = [
  { label: "Architect Construction Manager", rows: 23, grain: "construction-manager" },
  { label: "Engineer Construction Manager", rows: 66, grain: "construction-manager" },
  { label: "General Construction Manager", rows: 511, grain: "construction-manager" },
  { label: "General Contractor", rows: 11161, grain: "license-category" },
  { label: "General Primary Qualifying Party", rows: 11743, grain: "qualifying-party" },
  { label: "General Qualifying Party", rows: 317, grain: "qualifying-party" },
  { label: "Mechanical Construction Manager", rows: 38, grain: "construction-manager" },
  { label: "Mechanical Contractor", rows: 7988, grain: "license-category" },
  { label: "Mechanical Primary Qualifying Party", rows: 8707, grain: "qualifying-party" },
  { label: "Mechanical Qualifying Party", rows: 310, grain: "qualifying-party" },
  { label: "Alarm Registered Employee", rows: 5854, grain: "registered-employee" },
  { label: "Burglar Alarm BranchCompany", rows: 24, grain: "license-category" },
  { label: "Burglar Alarm Company", rows: 531, grain: "license-category" },
  { label: "Burglar Alarm Primary Qualifying Party", rows: 553, grain: "qualifying-party" },
  { label: "Burglar Alarm Extra Qualifying Party", rows: 64, grain: "qualifying-party" },
  { label: "Fire Alarm Company", rows: 399, grain: "license-category" },
  { label: "Fire Alarm Primary Qualifying Party", rows: 553, grain: "qualifying-party" },
  { label: "Fire Alarm Extra Qualifying Party", rows: 73, grain: "qualifying-party" },
  { label: "Fire Sprinkler Company", rows: 250, grain: "license-category" },
  { label: "Fire Sprinkler Branch Company", rows: 31, grain: "license-category" },
  { label: "Fire Sprinkler Primary Qualifying Party", rows: 270, grain: "qualifying-party" },
  { label: "Fire Sprinkler Extra Qualifying Party", rows: 47, grain: "qualifying-party" },
] as const;

export const SC_RBC_CATEGORIES = [
  { label: "COA Certificate of Authorization", rows: 405, grain: "firm-certificate" },
  { label: "Electrical", rows: 1269, grain: "residential-specialty-license" },
  { label: "Home Builders", rows: 7231, grain: "license-category" },
  { label: "HVAC Heating and Air", rows: 842, grain: "residential-specialty-license" },
  { label: "Plumbing", rows: 903, grain: "residential-specialty-license" },
  { label: "RB Exam Waiver", rows: 650, grain: "license-category" },
  { label: "Residential Non-Mechanical", rows: 57, grain: "license-category" },
  { label: "Specialty", rows: 10779, grain: "registration-category" },
] as const;

const clbListedSum = SC_CLB_CATEGORIES.reduce((sum, row) => sum + row.rows, 0);
const rbcReadableSum = SC_RBC_CATEGORIES.reduce((sum, row) => sum + row.rows, 0);

export const SC_SNAPSHOT = {
  regulator: "South Carolina Department of Labor, Licensing and Regulation",
  reportUrl: "https://llr.sc.gov/AboutUs/MediaCenter/annreport/2024-2025-LLR-Annual-Report.pdf",
  reportTitle: "Annual Report Fiscal Year 2025",
  reportPeriodStart: "2024-07-01",
  reportPeriodEnd: "2025-06-30",
  reportSha256: "51d2b2ff46770efbb85ee9a72c29e4b225379a0be7bd1e632ff260cbf861473e",
  reportBytes: 2857515,
  clbUrl: "https://llr.sc.gov/clb/",
  rbcUrl: "https://llr.sc.gov/res/",
  searchUrl: "https://verify.llronline.com/LicLookup/Contractors/Contractor.aspx",
  residentialListPage: "https://llr.sc.gov/res/licensure.aspx",
  clbStatute: "S.C. Code Ann. § 40-11-5 et seq.",
  alarmStatute: "S.C. Code Ann. § 40-79-5 et seq.",
  sprinklerStatute: "S.C. Code Ann. § 40-10-5 et seq.",
  rbcStatute: "S.C. Code Ann. § 40-59-5 et seq.",
  retrievedAt: "2026-10-05",
  publishedAt: "2026-10-05",
  clbPrintedTotal: 49355,
  clbListedCategorySum: clbListedSum,
  clbPrintedTotalEqualsListedRows: clbListedSum === 49355,
  generalContractorRows: 11161,
  mechanicalContractorRows: 7988,
  rbcPrintedTotal: 23796,
  rbcReadableCategorySum: rbcReadableSum,
  rbcPrintedTotalEqualsReadableRows: rbcReadableSum === 23796,
  homeInspectorPrinted: "1,60",
  homeInspectorCount: null,
  homeBuildersRows: 7231,
  residentialElectricalRows: 1269,
  residentialHvacRows: 842,
  residentialPlumbingRows: 903,
  residentialSpecialtyRegistrationRows: 10779,
  coaRows: 405,
  clbComplaintsReceived: 714,
  clbInvestigations: 656,
  clbDispositions: 220,
  rbcComplaintsReceived: 882,
  rbcInvestigations: 969,
  rbcDispositions: 642,
  licenseRoster: "NOT_ACQUIRED",
  licenseeListRequest: "NOT_FILED",
  classifications: "NOT_ON_THIS_REPORT",
  expiration: "NOT_ON_THIS_REPORT",
  businessVersusPersonOnContractorRows: "NOT_PRINTED",
  statusPrinted: false,
  localLicenses: "NOT_STATEWIDE",
  buildingCodesCouncilUsed: false,
  newCanonicalCompanies: 0,
  graphWrites: 0,
  claimEligibilityChanges: 0,
} as const;
