import type { PublicBusinessProfile } from "@/lib/business-profile/public-contract";
import React from "react";
import { BusinessProfileAnalytics } from "./BusinessProfileAnalytics";

const DAYS = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
const formatTime = (value?: string) => value ? new Date(`2000-01-01T${value}:00`).toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" }) : "";

export function BusinessSuppliedProfile({ profile, officialFormationDate }: { profile: PublicBusinessProfile; officialFormationDate?: string | null }) {
  const f = profile.fields;
  return <section aria-labelledby="business-supplied-heading" className="rounded-2xl border border-[var(--border)] bg-white p-5 shadow-sm sm:p-6">
    <BusinessProfileAnalytics profileId={profile.nativeProfileId} freshness={profile.freshness.state} />
    <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-[var(--accent)]">Managed by the business</p><h2 id="business-supplied-heading" className="mt-1 text-xl font-semibold text-[var(--text)]">Information provided by the business</h2></div><p className="text-sm text-[var(--muted)]">{profile.freshness.label}</p></div>
    <p className="mt-3 max-w-3xl text-sm leading-relaxed text-[var(--muted)]">This business manages the information it provides on this profile. Licensing, regulatory records, and TrustHub research remain independently sourced.</p>
    {f.description ? <div className="mt-5"><h3 className="font-semibold text-[var(--text)]">About</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-relaxed text-[var(--text)]">{f.description}</p></div> : null}
    <div className="mt-5 grid gap-5 md:grid-cols-2">
      {(f.website || f.public_phone || f.public_email || f.contact_context) ? <div><h3 className="font-semibold text-[var(--text)]">Contact information</h3><p className="mt-1 text-xs text-[var(--muted)]">Provided by the business</p><dl className="mt-2 space-y-2 text-sm">{f.website ? <div><dt className="text-[var(--muted)]">Website</dt><dd><a className="underline" href={f.website} target="_blank" rel="noopener noreferrer nofollow">Visit business website</a></dd></div> : null}{f.public_phone ? <div><dt className="text-[var(--muted)]">Phone</dt><dd><a href={`tel:${f.public_phone.replace(/[^\d+]/g, "")}`}>{f.public_phone}</a></dd></div> : null}{f.public_email ? <div><dt className="text-[var(--muted)]">Email</dt><dd><a href={`mailto:${f.public_email}`}>{f.public_email}</a></dd></div> : null}{f.contact_context ? <div><dt className="text-[var(--muted)]">Contact notes</dt><dd>{f.contact_context}</dd></div> : null}</dl></div> : null}
      {(profile.services.length || profile.serviceAreas.length || profile.languages.length) ? <div className="space-y-4">{profile.services.length ? <div><h3 className="font-semibold text-[var(--text)]">Services described by the business</h3><p className="mt-1 text-sm">{profile.services.join(" · ")}</p></div> : null}{profile.serviceAreas.length ? <div><h3 className="font-semibold text-[var(--text)]">Service area provided by the business</h3><p className="mt-1 text-sm">{profile.serviceAreas.join(" · ")}</p><p className="mt-1 text-xs text-[var(--muted)]">This is not a statement of license authority.</p></div> : null}{profile.languages.length ? <div><h3 className="font-semibold text-[var(--text)]">Languages</h3><p className="mt-1 text-sm">{profile.languages.join(" · ")}</p></div> : null}</div> : null}
      {f.founded_year ? <div><h3 className="font-semibold text-[var(--text)]">Business history</h3><dl className="mt-2 space-y-2 text-sm"><div><dt className="text-[var(--muted)]">Founded year provided by the business</dt><dd>{f.founded_year}</dd></div>{officialFormationDate ? <div><dt className="text-[var(--muted)]">Official Florida entity filing date</dt><dd>{new Date(officialFormationDate).toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric", timeZone: "UTC" })}</dd></div> : null}</dl></div> : null}
      {(profile.hours.length || f.emergency_service) ? <div><h3 className="font-semibold text-[var(--text)]">Availability provided by the business</h3>{profile.hours.length ? <ul className="mt-2 space-y-1 text-sm">{profile.hours.map((h) => <li key={h.weekday}>{DAYS[h.weekday]}: {h.closed ? "Closed" : `${formatTime(h.opensAt)}–${formatTime(h.closesAt)}`}</li>)}</ul> : null}{f.emergency_service === "true" ? <p className="mt-2 text-sm">Emergency service reported as available. Response is not guaranteed.</p> : f.emergency_service === "false" ? <p className="mt-2 text-sm">Emergency service reported as unavailable.</p> : null}</div> : null}
    </div>
  </section>;
}
