import network from "@/data/home/contractor-network-metrics-v1.json";
import az from "@/lib/arizona-intelligence/accepted-snapshot.json";
import ca from "@/lib/california-intelligence/accepted-snapshot.json";
import caLocal from "@/lib/california-intelligence/local/accepted-snapshot.json";
import nj from "@/lib/new-jersey-intelligence/accepted-snapshot.json";
import tx from "@/lib/texas-intelligence/accepted-snapshot.json";
import txLocal from "@/lib/texas-intelligence/local/accepted-snapshot.json";
import wa from "@/lib/washington-intelligence/accepted-snapshot.json";

export type HomepageEvidenceFamily = "License / registration" | "Regulatory / enforcement" | "Permit / construction / work history" | "Financial responsibility" | "Business evidence" | "Public research surfaces";
export type HomepageEvidenceItem = { id: string; family: HomepageEvidenceFamily; label: string; count: number; grain: string; geography: string; artifact: string; sourceAsOf: string; counts: string; doesNotCount: string; href?: string };

const metric = (key: string) => {
  const row = network.metrics.find((item) => item.key === key);
  if (!row) throw new Error(`Missing accepted network metric: ${key}`);
  return row;
};
const generated = network.generatedAt.slice(0, 10);

export const HOMEPAGE_EVIDENCE_INVENTORY: readonly HomepageEvidenceItem[] = [
  { id: "live-credentials", family: "License / registration", label: "Live credential records", count: metric("live_credential_records").value, grain: metric("live_credential_records").grain, geography: "Live public state cohort", artifact: "contractor-network-metrics-v1", sourceAsOf: "Board source clocks vary", counts: "License and registration rows in live public source systems.", doesNotCount: "Unique companies, recommendations, or every U.S. contractor." },
  { id: "research-graph-licenses", family: "License / registration", label: "Research-graph license records", count: metric("research_graph_license_records").value, grain: metric("research_graph_license_records").grain, geography: "Populated research graph", artifact: "contractor-network-metrics-v1", sourceAsOf: "Board source clocks vary", counts: "License rows across populated source systems.", doesNotCount: "The live public cohort or unique businesses." },
  { id: "az-current", family: "License / registration", label: "Arizona ROC current licenses", count: az.current_posting.all_current, grain: "ROC current-posting license row", geography: "Arizona", artifact: "AZ-CON-001 accepted snapshot", sourceAsOf: az.current_posting.header_as_of, counts: "License rows on ROC’s All Current Contractors posting.", doesNotCount: "Unique companies; Commercial, Residential, and Dual files are not additive.", href: "/arizona" },
  { id: "wa-registrations", family: "License / registration", label: "Washington L&I registrations", count: wa.general.rows, grain: wa.general.grain, geography: "Washington", artifact: "WA-CON-001 accepted snapshot", sourceAsOf: wa.general.source_clock.slice(0, 10), counts: "Source-native contractor registration/license numbers.", doesNotCount: "Quality, person trade certificates, or unique UBI entities.", href: "/washington" },
  { id: "ca-license-master", family: "License / registration", label: "California acquired CSLB rows", count: ca.license_master.license_rows, grain: "acquired partial License Master row", geography: "California", artifact: "CA-CON-002 accepted snapshot", sourceAsOf: ca.as_of, counts: "Rows acquired from the CSLB License Master stream.", doesNotCount: "The complete renewable CSLB universe; the stream is truncated.", href: "/california" },
  { id: "tx-business-credentials", family: "License / registration", label: "Texas TDLR business credentials", count: tx.hero.universe_value, grain: "specialty business credential", geography: "Texas", artifact: "TX-CON-001 accepted snapshot", sourceAsOf: tx.as_of, counts: "TDLR specialty/company contractor credentials.", doesNotCount: "All Texas contractors or a statewide general-contractor class.", href: "/texas" },

  { id: "regulatory-actions", family: "Regulatory / enforcement", label: "Indexed regulatory and enforcement rows", count: metric("regulatory_discipline_action_rows").value, grain: metric("regulatory_discipline_action_rows").grain, geography: "FL-heavy plus NJ and AZ indexed families", artifact: "contractor-network-metrics-v1", sourceAsOf: generated, counts: "Family-separated discipline and enforcement source rows.", doesNotCount: "Bad contractors, convictions, or a clean-record denominator." },
  ...network.evidenceFamilies.filter((row) => row.sourceSystem === "fl_dbpr" || row.sourceSystem === "fl_dfs").map((row): HomepageEvidenceItem => ({ id: row.key, family: "Regulatory / enforcement", label: row.label, count: row.rows, grain: row.grain, geography: "Florida", artifact: "contractor-network-metrics-v1 evidenceFamilies", sourceAsOf: generated, counts: "An accepted official-source evidence-family row.", doesNotCount: "Unique contractors, current status, or criminal convictions.", href: "/florida" })),
  { id: "nj-public-works-regulatory", family: "Regulatory / enforcement", label: "NJ public-works regulatory rows", count: nj.hero.observations_value, grain: "family-separated public-works regulatory source row", geography: "New Jersey", artifact: "NJ-CON-004 accepted snapshot", sourceAsOf: nj.as_of, counts: "WALL, Wage Watchlist, and Treasury construction/vendor rows retained by family.", doesNotCount: "Unique contractors, proven exact matches, or one combined severity scale.", href: "/new-jersey" },
  { id: "az-discipline", family: "Regulatory / enforcement", label: "Arizona ROC discipline rows", count: az.discipline.pre_ingest_graph_rows, grain: "ROC disciplinary action row", geography: "Arizona", artifact: "AZ-CON-001 accepted snapshot", sourceAsOf: az.as_of, counts: "Disciplinary rows already in the research graph.", doesNotCount: "Complaints, quality, or proof that no row means a clean history.", href: "/arizona" },

  { id: "indexed-permits", family: "Permit / construction / work history", label: "Indexed permit-source records", count: metric("indexed_permit_source_records").value, grain: metric("indexed_permit_source_records").grain, geography: "Selected indexed permit sources", artifact: "contractor-network-metrics-v1", sourceAsOf: generated, counts: "Rows in production permit_source_records.", doesNotCount: "NJ construction rows, unique projects, or completed jobs." },
  { id: "nj-construction", family: "Permit / construction / work history", label: "New Jersey construction source records", count: nj.hero.universe_value, grain: "permit-issued or certificate-issued source record", geography: "New Jersey municipalities", artifact: "NJ-CON-004 accepted snapshot", sourceAsOf: nj.hero.current_value, counts: "DCA permit-issued and certificate-issued source records.", doesNotCount: "2.68 million unique permits, projects, contractors, or credentials.", href: "/new-jersey" },
  { id: "austin-permits", family: "Permit / construction / work history", label: "Austin issued permit rows", count: txLocal.austin.rows, grain: txLocal.austin.grain, geography: "City of Austin—not Travis County or metro", artifact: "TX-CON-LOCAL-002 accepted snapshot", sourceAsOf: txLocal.as_of, counts: "City-issued construction permit rows.", doesNotCount: "State licenses, unique contractors, quality, or statewide Texas activity.", href: "/texas/austin" },
  { id: "sf-permits", family: "Permit / construction / work history", label: "San Francisco permit rows", count: caLocal.san_francisco.permits.rows, grain: caLocal.san_francisco.permits.grain, geography: "City and County of San Francisco", artifact: "CA-CON-COUNTY-002 accepted snapshot", sourceAsOf: caLocal.san_francisco.permits.as_of, counts: "Permit records at address grain.", doesNotCount: "Contractor quality, statewide permits, or exact CSLB attribution.", href: "/california/san-francisco" },
  { id: "la-current-permits", family: "Permit / construction / work history", label: "Los Angeles current permit rows", count: caLocal.los_angeles.current_permits_2020_present.rows, grain: caLocal.los_angeles.current_permits_2020_present.grain, geography: "City of Los Angeles—not LA County", artifact: "CA-CON-COUNTY-002 accepted snapshot", sourceAsOf: caLocal.los_angeles.current_permits_2020_present.as_of, counts: "Issued building permit rows in the current local source.", doesNotCount: "A statewide permit census or exact contractor-license matches.", href: "/california/los-angeles" },
  { id: "la-cofo", family: "Permit / construction / work history", label: "Los Angeles occupancy certificates", count: caLocal.los_angeles.cofo.rows, grain: caLocal.los_angeles.cofo.grain, geography: "City of Los Angeles", artifact: "CA-CON-COUNTY-002 accepted snapshot", sourceAsOf: caLocal.los_angeles.cofo.as_of, counts: "Certificate-of-occupancy source rows.", doesNotCount: "Permits, projects, quality, or unique contractors." },

  { id: "wa-bond-rows", family: "Financial responsibility", label: "Washington bond filing rows", count: wa.bond.rows, grain: wa.bond.grain, geography: "Washington", artifact: "WA-CON-001 accepted snapshot", sourceAsOf: wa.bond.source_clock.slice(0, 10), counts: "Bond filing rows associated with L&I contractor numbers.", doesNotCount: "Unique contractors, endorsements, or guaranteed current bonds." },
  { id: "wa-bond-identities", family: "Financial responsibility", label: "Washington IDs with bond evidence", count: wa.bond.distinct_contractor_ids, grain: "distinct ContractorLicenseNumber with bond evidence", geography: "Washington", artifact: "WA-CON-001 accepted snapshot", sourceAsOf: wa.bond.source_clock.slice(0, 10), counts: "Exact contractor IDs appearing in the bond file.", doesNotCount: "Bond rows or proof missing IDs are unbonded." },
  { id: "wa-insurance-rows", family: "Financial responsibility", label: "Washington insurance filing rows", count: wa.insurance.rows, grain: wa.insurance.grain, geography: "Washington", artifact: "WA-CON-001 accepted snapshot", sourceAsOf: wa.insurance.source_clock.slice(0, 10), counts: "Liability-insurance filing rows associated with L&I contractor numbers.", doesNotCount: "Unique contractors, safety, or guaranteed current coverage." },
  { id: "wa-insurance-identities", family: "Financial responsibility", label: "Washington IDs with insurance evidence", count: wa.insurance.distinct_contractor_ids, grain: "distinct ContractorLicenseNumber with insurance evidence", geography: "Washington", artifact: "WA-CON-001 accepted snapshot", sourceAsOf: wa.insurance.source_clock.slice(0, 10), counts: "Exact contractor IDs appearing in the insurance file.", doesNotCount: "Insurance rows or proof missing IDs are uninsured." },
  { id: "wa-both-identities", family: "Financial responsibility", label: "Washington IDs with bond + insurance evidence", count: wa.graph.ids_with_both, grain: "distinct ContractorLicenseNumber in both filing files", geography: "Washington", artifact: "WA-CON-001 accepted snapshot", sourceAsOf: wa.as_of, counts: "Exact IDs present in General, Bond, and Insurance files.", doesNotCount: "A score, endorsement, or proof of quality." },

  { id: "graph-contacts", family: "Business evidence", label: "Public contact observations", count: metric("public_contact_observations").value, grain: metric("public_contact_observations").grain, geography: "Research graph", artifact: "contractor-network-metrics-v1", sourceAsOf: generated, counts: "Published contact observation rows.", doesNotCount: "Contractor identities, licenses, or service areas." },
  { id: "wa-phones", family: "Business evidence", label: "Washington public business phones", count: wa.contacts.phone_public_eligible, grain: "source-published business phone field", geography: "Washington", artifact: "WA-CON-001 accepted snapshot", sourceAsOf: wa.as_of, counts: "Public-eligible phone fields on L&I registration rows.", doesNotCount: "Personal contacts, verified service areas, or unique businesses." },
  { id: "wa-principals", family: "Business evidence", label: "Washington principal rows", count: wa.principals.rows, grain: "principal relationship row", geography: "Washington", artifact: "WA-CON-001 accepted snapshot", sourceAsOf: wa.principals.source_clock.slice(0, 10), counts: "Owner/member/partner/officer relationships published by L&I.", doesNotCount: "Unique people, qualifying licenses, or endorsements." },
  { id: "az-addresses", family: "Business evidence", label: "Arizona official business addresses", count: az.contacts.business_address.count, grain: "business address on ROC license row", geography: "Arizona", artifact: "AZ-CON-001 accepted snapshot", sourceAsOf: az.as_of, counts: "Public-eligible business addresses published by ROC.", doesNotCount: "Mailing addresses, service areas, or unique companies." },
  { id: "az-qualifiers", family: "Business evidence", label: "Arizona named qualifying-party fields", count: az.qualifying_party.named, grain: az.qualifying_party.grain, geography: "Arizona", artifact: "AZ-CON-001 accepted snapshot", sourceAsOf: az.as_of, counts: "Named qualifying-party strings on license rows.", doesNotCount: "Unique people, owners, or person profiles." },
  { id: "tx-vendors", family: "Business evidence", label: "Texas construction-related CMBL vendors", count: tx.cmbl.construction_vendor_rows, grain: "construction-related procurement vendor row", geography: "Texas", artifact: "TX-CON-001 accepted snapshot", sourceAsOf: tx.as_of, counts: "CMBL vendors selected by accepted construction codes/categories.", doesNotCount: "Contractor licenses or proof unmatched vendors are unlicensed." },
  { id: "wa-public-works", family: "Business evidence", label: "Washington public-works project rows", count: wa.public_works.project_details.rows, grain: "public-works project-detail row", geography: "Washington", artifact: "WA-CON-001 accepted snapshot", sourceAsOf: wa.as_of, counts: "Project-detail rows carrying Prime Contractor UBI.", doesNotCount: "Registrations, unique contractors, awards as quality, or a published directory." },

  { id: "state-pages", family: "Public research surfaces", label: "Completed state intelligence pages", count: 6, grain: "published state intelligence route", geography: "FL · NJ · CA · TX · WA · AZ", artifact: "Accepted state publication snapshots", sourceAsOf: "2026-09-04", counts: "The six completed intelligence destinations featured on the homepage.", doesNotCount: "All live Verify states or a research-depth rating." },
  { id: "county-pages", family: "Public research surfaces", label: "Published FL/NJ county intelligence pages", count: metric("published_county_intelligence_pages").value, grain: metric("published_county_intelligence_pages").grain, geography: "Selected Florida and New Jersey counties", artifact: "contractor-network-metrics-v1", sourceAsOf: metric("published_county_intelligence_pages").sourceAsOf ?? generated, counts: "Published county intelligence routes.", doesNotCount: "Municipalities, state pages, or California city pages." },
  { id: "ca-city-pages", family: "Public research surfaces", label: "Published California city intelligence pages", count: metric("published_ca_city_local_intelligence_pages").value, grain: metric("published_ca_city_local_intelligence_pages").grain, geography: "San Francisco and City of Los Angeles", artifact: "contractor-network-metrics-v1 + CA local accepted snapshot", sourceAsOf: metric("published_ca_city_local_intelligence_pages").sourceAsOf ?? caLocal.as_of, counts: "Published local city intelligence routes.", doesNotCount: "County pages or statewide permit coverage." },
  { id: "austin-page", family: "Public research surfaces", label: "Published Texas local intelligence page", count: txLocal.publication.dedicated.length, grain: "published city intelligence route", geography: "City of Austin", artifact: "TX-CON-LOCAL-002 accepted snapshot", sourceAsOf: txLocal.as_of, counts: "Dedicated published Texas local intelligence routes.", doesNotCount: "Parked local harvests or statewide coverage." },
] as const;

export const HOMEPAGE_EVIDENCE_FAMILIES = ["License / registration", "Regulatory / enforcement", "Permit / construction / work history", "Financial responsibility", "Business evidence", "Public research surfaces"] as const;

export function homepageEvidenceByFamily() {
  return HOMEPAGE_EVIDENCE_FAMILIES.map((family) => ({ family, items: HOMEPAGE_EVIDENCE_INVENTORY.filter((item) => item.family === family) }));
}
