/** MS-CON-001: recount of the saved MSBOC export already loaded as ms_sbc. No new load. */
export const MS_SNAPSHOT = {
  regulator: "Mississippi State Board of Contractors",
  searchUrl: "http://search.msboc.us/ConsolidatedSearch.cfm",
  resultsUrl: "http://search.msboc.us/ConsolidatedResults.cfm",
  verifyPath: "/verify?state=ms",
  fileName: "msboc_results.xls",
  fileBytes: 2490818,
  fileSha256: "b5683292c881dbf895cefd2cd5a88960994eaeec5f6b56ea48b4c2bee0979988",
  fileDate: "2026-08-14",
  recountedAt: "2026-10-05",
  listRows: 8244,
  uniqueKeys: 8242,
  duplicateKeysDropped: 2,
  licensed: 3425,
  licensedExpired: 4544,
  unlicensed: 152,
  unlicensedExpired: 105,
  revoked: 14,
  suspended: 2,
  typeCommercial: 5154,
  typeResidential: 2902,
  typeResidentialInactiveLabel: 140,
  typeCommercialInactiveLabel: 46,
  occupationRes: 3042,
  occupationMc: 2220,
  occupationSc: 1890,
  occupationCom: 1090,
  mailingMs: 4505,
  mailingBlank: 20,
  mailingOther: 3719,
  distinctNameStrings: 7922,
  classCodeColumn: "NOT_IN_THIS_EXPORT",
  qualifierColumn: "NOT_IN_THIS_EXPORT",
  countyColumn: "NOT_IN_THIS_EXPORT",
  expirationColumn: "NOT_IN_THIS_EXPORT",
  issueDateColumn: "NOT_IN_THIS_EXPORT",
  violationsCorpus: "NOT_ACQUIRED",
  businessPersonGrain: "NOT_LABELED",
  secondaryBoards: "NOT_ACQUIRED",
  netNewEntities: 0,
  graphWrites: 0,
  databaseReread: false,
} as const;

/** Occupation code is derived from the published type and the license-number suffix. It is not a ClassCode column. */
export const MS_STATUS_BY_CLASS = [
  { code: "COM", label: "Commercial, no -MC or -SC suffix", status: "Licensed", rows: 5 },
  { code: "COM", label: "Commercial, no -MC or -SC suffix", status: "Licensed Expired", rows: 918 },
  { code: "COM", label: "Commercial, no -MC or -SC suffix", status: "Revoked", rows: 3 },
  { code: "COM", label: "Commercial, no -MC or -SC suffix", status: "Unlicensed", rows: 85 },
  { code: "COM", label: "Commercial, no -MC or -SC suffix", status: "Unlicensed Expired", rows: 79 },
  { code: "MC", label: "Commercial major, license suffix -MC", status: "Licensed", rows: 1191 },
  { code: "MC", label: "Commercial major, license suffix -MC", status: "Licensed Expired", rows: 1029 },
  { code: "RES", label: "Residential, including the inactive type label", status: "Licensed", rows: 1350 },
  { code: "RES", label: "Residential, including the inactive type label", status: "Licensed Expired", rows: 1586 },
  { code: "RES", label: "Residential, including the inactive type label", status: "Revoked", rows: 11 },
  { code: "RES", label: "Residential, including the inactive type label", status: "Suspended", rows: 2 },
  { code: "RES", label: "Residential, including the inactive type label", status: "Unlicensed", rows: 67 },
  { code: "RES", label: "Residential, including the inactive type label", status: "Unlicensed Expired", rows: 26 },
  { code: "SC", label: "Commercial specialty, license suffix -SC", status: "Licensed", rows: 879 },
  { code: "SC", label: "Commercial specialty, license suffix -SC", status: "Licensed Expired", rows: 1011 },
] as const;

export const MS_MAILING_STATES = [
  { value: "MS", rows: 4505 },
  { value: "TN", rows: 630 },
  { value: "AL", rows: 579 },
  { value: "LA", rows: 554 },
  { value: "TX", rows: 384 },
  { value: "GA", rows: 266 },
  { value: "FL", rows: 222 },
  { value: "AR", rows: 158 },
  { value: "blank", rows: 20 },
  { value: "other printed", rows: 926 },
] as const;
