/** OK-CON-001: CIB publishes searches, not a bulk roster. General contracting is not a statewide license. */
export const OK_SNAPSHOT = {
  regulator: "Oklahoma Construction Industries Board",
  faqUrl: "https://oklahoma.gov/cib/frequently-asked-questions.html",
  faqLastModified: "2025-12-30",
  requirementsUrl: "https://oklahoma.gov/cib/your-industry/active-contractor-requirements.html",
  requirementsLastModified: "2026-05-14",
  lookupUrl: "https://oklahoma.gov/cib/consumers/are-they-licensed.html",
  lookupLastModified: "2026-09-18",
  roofingSearchUrl: "https://verify.cib.hbesystems.com/roofing/search",
  tradeSearchUrl:
    "https://okcibv7prod.glsuite.us/GLSuiteWeb/Clients/OKCIB/Public/LicenseeSearch/LicenseeSearch.aspx",
  retrievedAt: "2026-10-06",
  statewideGeneralContractorLicense: "NOT_ISSUED",
  bulkRosters: "NOT_ACQUIRED",
  bondRequirementUsd: 5000,
  liabilityRequirementUsd: 50000,
  observedBondOrInsurance: "NOT_ACQUIRED",
  electricalWorkersCompProof: "REQUIREMENT_NOT_OBSERVED_COMPLIANCE",
  enforcementCorpus: "NOT_ACQUIRED",
  complaintCorpus: "NOT_ACQUIRED",
  permitsIssuedByCib: false,
  newCanonicalEntities: 0,
  graphWrites: 0,
  classes: [
    {
      id: "electrical-contractor",
      label: "Electrical contractor",
      level: "Contractor",
      grain: "Individual license holder",
      search: "GLSuite licensee search",
      roster: "NOT_ACQUIRED",
    },
    {
      id: "electrical-journeyman",
      label: "Electrical journeyman",
      level: "Journeyman",
      grain: "Person",
      search: "GLSuite licensee search",
      roster: "NOT_ACQUIRED",
    },
    {
      id: "electrical-apprentice",
      label: "Electrical apprentice",
      level: "Apprentice registration",
      grain: "Person",
      search: "Application, not a published roster",
      roster: "NOT_ACQUIRED",
    },
    {
      id: "mechanical-contractor",
      label: "Mechanical contractor",
      level: "Contractor",
      grain: "Individual license holder",
      search: "GLSuite licensee search",
      roster: "NOT_ACQUIRED",
    },
    {
      id: "mechanical-journeyman",
      label: "Mechanical journeyman",
      level: "Journeyman",
      grain: "Person",
      search: "GLSuite licensee search",
      roster: "NOT_ACQUIRED",
    },
    {
      id: "mechanical-apprentice",
      label: "Mechanical apprentice",
      level: "Apprentice registration",
      grain: "Person",
      search: "Application, not a published roster",
      roster: "NOT_ACQUIRED",
    },
    {
      id: "plumbing-contractor",
      label: "Plumbing contractor",
      level: "Contractor",
      grain: "Individual license holder",
      search: "GLSuite licensee search",
      roster: "NOT_ACQUIRED",
    },
    {
      id: "plumbing-journeyman",
      label: "Plumbing journeyman",
      level: "Journeyman",
      grain: "Person",
      search: "GLSuite licensee search",
      roster: "NOT_ACQUIRED",
    },
    {
      id: "roofing",
      label: "Roofing",
      level: "Registered roofing contractor",
      grain: "Separate roofing search",
      search: "HBES roofing search",
      roster: "NOT_ACQUIRED",
    },
    {
      id: "building-inspector",
      label: "Building and construction inspector",
      level: "Inspector",
      grain: "Person employed by a political subdivision",
      search: "GLSuite licensee search",
      roster: "NOT_ACQUIRED",
    },
    {
      id: "home-inspector",
      label: "Home inspector",
      level: "Home inspector",
      grain: "Person",
      search: "GLSuite licensee search",
      roster: "NOT_ACQUIRED",
    },
  ],
} as const;
