-- TH-SEARCH-R1-019B-P2E -- PROPOSED, NOT APPLIED. Stage A of the reviewed transition only.
-- Generated by scripts/th_search_r1_019b_p2e_generate_v2_ddl.ts from NORMALIZED_NAME_INDEXES (kind "words").
-- Five replacement token-tier GIN indexes on the WRAPPED expression (normalized || ''), under
-- TEMPORARY names. Deliberately no IF NOT EXISTS: an existing same-named object must stop the build.
-- Each statement must run alone, outside any transaction block, through the Session pooler (5432).
-- Run only through scripts/th_search_r1_019b_p2e_build_v2.mjs, which pins this file's sha256.
-- This file contains no DROP, no ALTER, no REINDEX, and nothing that touches a *_nameorder_idx index.

CREATE INDEX CONCURRENTLY contractors_display_name_namewords_v2_idx ON contractors USING gin (((' ' || btrim(regexp_replace(regexp_replace(upper(coalesce(display_name, '')), '[''`\u2018\u2019\u02BC]', '', 'g'), '[\x01-\x2F\x3A-\x40\x5B-\x60\x7B-\x7F\u00A0\u2013\u2014\u201C\u201D]+', ' ', 'g')) || ' ') || '') gin_trgm_ops) WHERE display_name IS NOT NULL;
CREATE INDEX CONCURRENTLY contractors_legal_name_namewords_v2_idx ON contractors USING gin (((' ' || btrim(regexp_replace(regexp_replace(upper(coalesce(legal_name, '')), '[''`\u2018\u2019\u02BC]', '', 'g'), '[\x01-\x2F\x3A-\x40\x5B-\x60\x7B-\x7F\u00A0\u2013\u2014\u201C\u201D]+', ' ', 'g')) || ' ') || '') gin_trgm_ops) WHERE legal_name IS NOT NULL;
CREATE INDEX CONCURRENTLY contractors_dba_name_namewords_v2_idx ON contractors USING gin (((' ' || btrim(regexp_replace(regexp_replace(upper(coalesce(dba_name, '')), '[''`\u2018\u2019\u02BC]', '', 'g'), '[\x01-\x2F\x3A-\x40\x5B-\x60\x7B-\x7F\u00A0\u2013\u2014\u201C\u201D]+', ' ', 'g')) || ' ') || '') gin_trgm_ops) WHERE dba_name IS NOT NULL;
CREATE INDEX CONCURRENTLY licenses_licensee_name_raw_namewords_v2_idx ON licenses USING gin (((' ' || btrim(regexp_replace(regexp_replace(upper(coalesce(licensee_name_raw, '')), '[''`\u2018\u2019\u02BC]', '', 'g'), '[\x01-\x2F\x3A-\x40\x5B-\x60\x7B-\x7F\u00A0\u2013\u2014\u201C\u201D]+', ' ', 'g')) || ' ') || '') gin_trgm_ops) WHERE licensee_name_raw IS NOT NULL;
CREATE INDEX CONCURRENTLY licenses_dba_name_raw_namewords_v2_idx ON licenses USING gin (((' ' || btrim(regexp_replace(regexp_replace(upper(coalesce(dba_name_raw, '')), '[''`\u2018\u2019\u02BC]', '', 'g'), '[\x01-\x2F\x3A-\x40\x5B-\x60\x7B-\x7F\u00A0\u2013\u2014\u201C\u201D]+', ' ', 'g')) || ' ') || '') gin_trgm_ops) WHERE dba_name_raw IS NOT NULL;
