/**
 * TH-SEARCH-R1-019B-P2E: renders docs/qa/th-search-r1-019b/PROPOSED-namewords-v2-indexes.sql from the
 * SAME code expression the candidate's token tier queries (NORMALIZED_NAME_INDEXES, kind "words"), so
 * the file cannot drift from the code. Touches no database. `--check` re-renders and compares bytes.
 *
 * Differences from the code's own DDL, both deliberate:
 *   1. the temporary name *_namewords_v2_idx -- the canonical names are still held in Production by
 *      the old bare-expression GIN indexes;
 *   2. no IF NOT EXISTS -- the transition is fail-closed: an unexpected same-named object must stop
 *      the build, never be silently skipped.
 */
import fs from "node:fs";
import { NORMALIZED_NAME_INDEXES } from "../lib/contractors/name-search-core";

const OUT = "docs/qa/th-search-r1-019b/PROPOSED-namewords-v2-indexes.sql";

const words = NORMALIZED_NAME_INDEXES.filter((index) => index.kind === "words");
if (words.length !== 5) throw new Error(`expected 5 token-tier indexes in code, found ${words.length}`);

const statements = words.map((index) => {
  if (!index.ddl.includes(" IF NOT EXISTS ")) throw new Error(`${index.name}: unexpected DDL shape`);
  if (!index.ddl.includes(" || '') gin_trgm_ops)")) throw new Error(`${index.name}: not on the wrapped token expression`);
  const v2Name = index.name.replace(/_namewords_idx$/, "_namewords_v2_idx");
  if (v2Name === index.name) throw new Error(`${index.name}: could not derive the v2 name`);
  const ddl = index.ddl.replace(" IF NOT EXISTS ", " ").split(index.name).join(v2Name);
  if (!ddl.startsWith(`CREATE INDEX CONCURRENTLY ${v2Name} ON ${index.table} USING gin (`)) throw new Error(`${v2Name}: rendered DDL has an unexpected shape`);
  return `${ddl};`;
});

const text = [
  "-- TH-SEARCH-R1-019B-P2E -- PROPOSED, NOT APPLIED. Stage A of the reviewed transition only.",
  "-- Generated by scripts/th_search_r1_019b_p2e_generate_v2_ddl.ts from NORMALIZED_NAME_INDEXES (kind \"words\").",
  "-- Five replacement token-tier GIN indexes on the WRAPPED expression (normalized || ''), under",
  "-- TEMPORARY names. Deliberately no IF NOT EXISTS: an existing same-named object must stop the build.",
  "-- Each statement must run alone, outside any transaction block, through the Session pooler (5432).",
  "-- Run only through scripts/th_search_r1_019b_p2e_build_v2.mjs, which pins this file's sha256.",
  "-- This file contains no DROP, no ALTER, no REINDEX, and nothing that touches a *_nameorder_idx index.",
  "",
  ...statements,
  "",
].join("\n");

if (process.argv.includes("--check")) {
  const onDisk = fs.readFileSync(OUT, "utf8");
  if (onDisk !== text) { console.error(`${OUT} differs from what the code renders. Regenerate and re-review.`); process.exit(1); }
  console.log(`${OUT} matches the code (5 statements).`);
} else {
  fs.writeFileSync(OUT, text);
  console.log(`wrote ${OUT} (5 statements)`);
}
