/** LSLBC Active roster certificate rows, not a deduplicated company census. */
export const LA_SNAPSHOT = {
  sourceDate: "2026-10-05",
  retrievedAt: "2026-10-05",
  retrievedAtUtc: "2026-10-05T13:15:57.451072+00:00",
  generatedAt: "2026-10-05",
  clockLabel:
    "Official LSLBC Active Request Roster re-pull on 2026-10-05. Not the 2026-08-14 production load, and not a graph rewrite.",
  rosterUrl: "https://arlspublic.lslbc.louisiana.gov/Public/RequestRoster",
  lookupUrl: "https://arlspublic.lslbc.louisiana.gov/Public/Search",
  homeUrl: "https://lslbc.gov/",
  certificates: [
    {
      code: "CLC",
      label: "Commercial License Certificate",
      grain: "license-certificate",
      status: "Active",
      rows: 19898,
      note: "Commercial license certificate. Not a universal contractor population.",
    },
    {
      code: "RLC",
      label: "Residential License Certificate",
      grain: "license-certificate",
      status: "Active",
      rows: 4701,
      note: "Residential license certificate. Separate from commercial.",
    },
    {
      code: "HIR",
      label: "Home Improvement Registration",
      grain: "registration",
      status: "Active",
      rows: 1501,
      note: "Home Improvement Registration is not a commercial or residential construction license by itself.",
    },
    {
      code: "MRL",
      label: "Mold Remediation License Certificate",
      grain: "specialty-certificate",
      status: "Active",
      rows: 269,
      note: "Mold Remediation License Certificate is a specialty certificate, not a general construction license.",
    },
  ],
  /** Sum of the four certificate-type rows. Not a company census and not an Ask total. */
  certificateRows: 26369,
  statusCounts: { Active: 26369 },
  duplicateLicenseKeys: 0,
  skippedRows: 0,
  classifications: "NOT_ACQUIRED",
  qualifyingParties: "NOT_ACQUIRED",
  plumbingBoardPersonLicenses: "NOT_ACQUIRED",
  expiredInactive: "NOT_IN_ACTIVE_EXPORT",
  disciplinaryRowsAcquired: 0,
  exactDisciplinaryAttachments: 0,
  nameOnlyAdverseJoins: 0,
  newCanonicalCompanies: 0,
  graphWrites: 0,
  claimEligibilityChanges: 0,
} as const;
